version: '3.7'

networks:
  laravel:

services:
  app:
    build:
      context: ./dockerfiles/development
      dockerfile: nginx.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: pto-api-nginx
    ports:
      - '${DOCKER_NGINX_PORT:-80}:80'
    volumes:
      - ./:/var/www/html:delegated
    depends_on:
      - php
      - redis
      - mysql
    networks:
      - laravel

  mysql:
    image: mariadb:10.6
    restart: unless-stopped
    container_name: pto-api-mysql
    tty: true
    ports:
      - '${DOCKER_MYSQL_PORT:-3306}:3306'
    volumes:
      - ./dockerfiles/development/mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
      - MYSQL_USER=${DOCKER_MYSQL_USER}
      - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
      - SERVICE_TAGS=${DOCKER_SERVICE_TAGS:-dev}
      - SERVICE_NAME=${DOCKER_SERVICE_NAME:-mysql}
    networks:
      - laravel

  php:
    build:
      context: ./dockerfiles/development
      dockerfile: php.dockerfile
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    container_name: pto-api-php-fpm
    ports:
      - "${DOCKER_PHP_FPM_PORT:-9000}:9000"
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - laravel

  redis:
    image: redis:alpine
    restart: unless-stopped
    container_name: pto-api-redis
    ports:
      - '${DOCKER_REDIS_PORT:-6379}:6379'
    networks:
      - laravel
