version: '3.7'

services:
    server-php:
        container_name: server-php
        hostname: server-php
        restart: unless-stopped
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            - .:/var/www/html
        networks:
            - server-network
        depends_on:
            - server-mysql

    server-nginx:
        image: nginx:1.23.1-alpine
        container_name: server-nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8080:80"
        volumes:
            - ./:/var/www/html
            - ./nginx/:/etc/nginx/conf.d/
        networks:
            - server-network
        depends_on:
            - server-php

    server-mysql:
        image: mariadb:10.5
        container_name: server-mysql
        restart: unless-stopped
        ports:
            - '${DOCKER_MYSQL_PORT:-3306}:3306'
        networks:
            - server-network
        environment:
            - MYSQL_DATABASE=${DOCKER_MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${DOCKER_MYSQL_ROOT_PASSWORD}
            - MYSQL_USER=${DOCKER_MYSQL_USER}
            - MYSQL_PASSWORD=${DOCKER_MYSQL_PASSWORD}
        hostname: mysql

networks:
    server-network:
        driver: bridge
